#!/bin/bash

# Invoke the Forever module (to START our Node.js server).
NODE_ENV=production PORT=3016 forever \
    start \
    -al forever-mca.log \
    -ao out-mca.log \
    -ae err-mca.log \
    --uid mca \
    app.js